[workspace]
members = [
  "CreuSAT",
  "Robinson",
  "Friday",
  "JigSAT",
  "tests",
]

[profile.release]
debug = false
#split-debuginfo = ?
debug-assertions = false
overflow-checks = false
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = false
rpath = false
