[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
disabled = true

[tasks.fmt]
disabled = true

[tasks.test]
disabled = true

[tasks.creusot-Friday]
workspace = false
command = "cargo"
args = ["creusot", "--", "-p", "Friday", "--features=${@}"]

[tasks.move-Friday]
workspace = false
script = '''
[ ! -f ./target/debug/Friday-rlib.mlcfg ] || cp ./target/debug/Friday-rlib.mlcfg ./mlcfgs/Friday.mlcfg
'''

[tasks.gen-cfg-Friday]
workspace = false
dependencies = ["creusot-Friday", "move-Friday"]

[tasks.ide-Friday]
workspace = false
script = '''
./ide ./mlcfgs/Friday.mlcfg
'''

[tasks.prove-Friday]
workspace = false
dependencies = ["gen-cfg-Friday", "ide-Friday"]

[tasks.creusot-Robinson]
workspace = false
command = "cargo"
args = ["creusot", "--", "-p", "Robinson", "--features=${@}"]

[tasks.move-Robinson]
workspace = false
script = '''
[ ! -f ./target/debug/Robinson-rlib.mlcfg ] || cp ./target/debug/Robinson-rlib.mlcfg ./mlcfgs/Robinson.mlcfg
'''

[tasks.gen-cfg-Robinson]
workspace = false
dependencies = ["creusot-Robinson", "move-Robinson"]

[tasks.ide-Robinson]
workspace = false
script = '''
./ide ./mlcfgs/Robinson.mlcfg
'''

[tasks.prove-Robinson]
workspace = false
dependencies = ["gen-cfg-Robinson", "ide-Robinson"]

[tasks.creusot-CreuSAT]
workspace = false
command = "cargo"
args = [
    "creusot",
    "--span-mode=relative",
    "--",
    "-p",
    "CreuSAT",
    "--features=${@}",
]

[tasks.move-CreuSAT]
workspace = false
script = '''
[ ! -f ./target/debug/CreuSAT-rlib.mlcfg ] || cp ./target/debug/CreuSAT-rlib.mlcfg ./mlcfgs/CreuSAT${@}.mlcfg
'''

[tasks.gen-cfg-CreuSAT]
workspace = false
dependencies = ["creusot-CreuSAT", "move-CreuSAT"]

[tasks.ide-CreuSAT]
workspace = false
script = '''
./ide ./mlcfgs/CreuSAT${@}.mlcfg
'''

[tasks.prove-CreuSAT]
workspace = false
dependencies = ["gen-cfg-CreuSAT", "ide-CreuSAT"]

[tasks.p]
workspace = false
dependencies = ["prove-CreuSAT"]
args = ["${@}"]

[tasks.build-musl]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo build --release --target x86_64-unknown-linux-musl
'''

[tasks.build-musl-mac]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo zigbuild --release --target x86_64-unknown-linux-musl
'''

[tasks.move-musl]
workspace = false
script = '''
cp ./target/x86_64-unknown-linux-musl/release/CreuSAT CreuSAT/StarExec/bin/creusat
'''

[tasks.make-zip]
workspace = false
script = '''
cd CreuSAT/StarExec && zip -r creusat.zip bin
'''

[tasks.build-musl-JigSAT-linux]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo build --release --target x86_64-unknown-linux-musl
'''

[tasks.build-musl-JigSAT-mac]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo zigbuild --release --target x86_64-unknown-linux-musl
'''

[tasks.move-musl-JigSAT]
workspace = false
script = '''
cp ./target/x86_64-unknown-linux-musl/release/JigSAT JigSAT/StarExec/bin/jigsat
'''

[tasks.make-zip-JigSAT]
workspace = false
script = '''
cd JigSAT/StarExec && zip -r jigsat.zip bin
'''

[tasks.StarExec-linux]
workspace = false
dependencies = ["build-musl", "move-musl", "make-zip"]

[tasks.StarExec-mac]
workspace = false
dependencies = ["build-musl-mac", "move-musl", "make-zip"]

[tasks.StarExec]
linux_alias = "StarExec-linux"
windows_alias = "StarExec-mac"
mac_alias = "StarExec-mac"

[tasks.StarExec-JigSAT-linux]
workspace = false
dependencies = [
    "build-musl-JigSAT-linux",
    "move-musl-JigSAT",
    "make-zip-JigSAT",
]

[tasks.StarExec-JigSAT-mac]
workspace = false
dependencies = ["build-musl-JigSAT-mac", "move-musl-JigSAT", "make-zip-JigSAT"]

[tasks.StarExec-JigSAT]
linux_alias = "StarExec-JigSAT-linux"
#linux_alias = "StarExec-JigSAT-mac"
windows_alias = "StarExec-JigSAT-mac"
mac_alias = "StarExec-JigSAT-mac"

[tasks.clean-Friday]
workspace = false
script = '''
rm -rf mlcfgs/Friday*
'''

[tasks.clean-Robinson]
workspace = false
script = '''
rm -rf mlcfgs/Robinson*
'''

[tasks.clean-CreuSAT]
workspace = false
script = '''
rm -rf mlcfgs/CreuSAT*
'''

[tasks.clean-proofs]
workspace = false
dependencies = ["clean-Friday", "clean-Robinson", "clean-CreuSAT"]


[tasks.creusot-Scratch]
workspace = false
command = "cargo"
args = ["creusot", "--", "-p", "Scratch", "--features=${@}"]

[tasks.move-Scratch]
workspace = false
script = '''
[ ! -f ./target/debug/Scratch-rlib.mlcfg ] || cp ./target/debug/Scratch-rlib.mlcfg ./mlcfgs/Scratch.mlcfg
'''

[tasks.gen-cfg-Scratch]
workspace = false
dependencies = ["creusot-Scratch", "move-Scratch"]

[tasks.ide-Scratch]
workspace = false
script = '''
./ide ./mlcfgs/Scratch.mlcfg
'''

[tasks.prove-Scratch]
workspace = false
dependencies = ["gen-cfg-Scratch", "ide-Scratch"]


[tasks.clean-Scratch]
workspace = false
script = '''
rm -rf mlcfgs/Scratch*
'''


[tasks.creusot-NewDB]
workspace = false
command = "cargo"
args = ["creusot", "--", "-p", "NewDB", "--features=${@}"]

[tasks.move-NewDB]
workspace = false
script = '''
[ ! -f ./target/debug/NewDB-rlib.mlcfg ] || cp ./target/debug/NewDB-rlib.mlcfg ./mlcfgs/NewDB.mlcfg
'''

[tasks.gen-cfg-NewDB]
workspace = false
dependencies = ["creusot-NewDB", "move-NewDB"]

[tasks.ide-NewDB]
workspace = false
script = '''
./ide ./mlcfgs/NewDB.mlcfg
'''

[tasks.prove-NewDB]
workspace = false
dependencies = ["gen-cfg-NewDB", "ide-NewDB"]


[tasks.clean-NewDB]
workspace = false
script = '''
rm -rf mlcfgs/NewDB*
'''

[tasks.n]
workspace = false
dependencies = ["prove-NewDB"]
args = ["${@}"]


[tasks.creusot-Abstract]
workspace = false
command = "cargo"
args = ["creusot", "--", "-p", "Abstract", "--features=${@}"]

[tasks.move-Abstract]
workspace = false
script = '''
[ ! -f ./target/debug/Abstract-rlib.mlcfg ] || cp ./target/debug/Abstract-rlib.mlcfg ./mlcfgs/Abstract.mlcfg
'''

[tasks.gen-cfg-Abstract]
workspace = false
dependencies = ["creusot-Abstract", "move-Abstract"]

[tasks.ide-Abstract]
workspace = false
script = '''
./ide ./mlcfgs/Abstract.mlcfg
'''

[tasks.prove-Abstract]
workspace = false
dependencies = ["gen-cfg-Abstract", "ide-Abstract"]


[tasks.clean-Abstract]
workspace = false
script = '''
rm -rf mlcfgs/Abstract*
'''

[tasks.a]
workspace = false
dependencies = ["prove-Abstract"]
args = ["${@}"]
