[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
disabled = true

[tasks.fmt]
disabled = true

[tasks.test]
disabled = true

[tasks.creusot-Friday]
workspace = false
command = "cargo"
args = ["creusot", "-p", "Friday", "--features=contracts", "--features", "${@}"]

[tasks.move-Friday]
workspace = false
script = '''
[ ! -f ./target/debug/Friday-rlib.mlcfg ] ||  mv ./target/debug/Friday-rlib.mlcfg ./mlcfgs/Friday.mlcfg
'''

[tasks.gen-cfg-Friday]
workspace = false
dependencies = [
    "creusot-Friday",
    "move-Friday",
]

[tasks.ide-Friday]
workspace = false
script = '''
~/creusot/ide ./mlcfgs/Friday.mlcfg
'''

[tasks.prove-Friday]
workspace = false
dependencies = [
    "gen-cfg-Friday",
    "ide-Friday",
]

[tasks.creusot-Robinson]
workspace = false
command = "cargo"
args = ["creusot", "-p", "Robinson", "--features=contracts", "--features", "${@}"]

[tasks.move-Robinson]
workspace = false
script = '''
[ ! -f ./target/debug/Robinson-rlib.mlcfg ] ||  mv ./target/debug/Robinson-rlib.mlcfg ./mlcfgs/Robinson.mlcfg
'''

[tasks.gen-cfg-Robinson]
workspace = false
dependencies = [
    "creusot-Robinson",
    "move-Robinson",
]

[tasks.ide-Robinson]
workspace = false
script = '''
~/creusot/ide ./mlcfgs/Robinson.mlcfg
'''

[tasks.prove-Robinson]
workspace = false
dependencies = [
    "gen-cfg-Robinson",
    "ide-Robinson",
]

[tasks.creusot-CreuSAT]
workspace = false
command = "cargo"
args = ["creusot", "-p", "CreuSAT", "--features=contracts", "--features", "${@}"]

[tasks.move-CreuSAT]
workspace = false
script = '''
[ ! -f ./target/debug/CreuSAT-rlib.mlcfg ] ||  mv ./target/debug/CreuSAT-rlib.mlcfg ./mlcfgs/CreuSAT.mlcfg
'''

[tasks.gen-cfg-CreuSAT]
workspace = false
dependencies = [
    "creusot-CreuSAT",
    "move-CreuSAT",
]

[tasks.ide-CreuSAT]
workspace = false
script = '''
~/creusot/ide ./mlcfgs/CreuSAT.mlcfg
'''

[tasks.prove-CreuSAT]
workspace = false
dependencies = [
    "gen-cfg-CreuSAT",
    "ide-CreuSAT",
]

[tasks.p]
workspace = false
dependencies = [
    "prove-CreuSAT",
]
args = [
    "${@}"
]
