[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
disabled = true

[tasks.fmt]
disabled = true

[tasks.test]
disabled = true

[tasks.creusot-Friday]
workspace = false
command = "cargo"
args = ["creusot", "-p", "Friday", "--features=contracts", "--features", "${@}"]

[tasks.move-Friday]
workspace = false
script = '''
[ ! -f ./target/debug/Friday-rlib.mlcfg ] || cp ./target/debug/Friday-rlib.mlcfg ./mlcfgs/Friday.mlcfg
'''

[tasks.gen-cfg-Friday]
workspace = false
dependencies = [
    "creusot-Friday",
    "move-Friday",
]

[tasks.ide-Friday]
workspace = false
script = '''
./ide ./mlcfgs/Friday.mlcfg
'''

[tasks.prove-Friday]
workspace = false
dependencies = [
    "gen-cfg-Friday",
    "ide-Friday",
]

[tasks.creusot-Robinson]
workspace = false
command = "cargo"
args = ["creusot", "-p", "Robinson", "--features=contracts", "--features", "${@}"]

[tasks.move-Robinson]
workspace = false
script = '''
[ ! -f ./target/debug/Robinson-rlib.mlcfg ] || cp ./target/debug/Robinson-rlib.mlcfg ./mlcfgs/Robinson.mlcfg
'''

[tasks.gen-cfg-Robinson]
workspace = false
dependencies = [
    "creusot-Robinson",
    "move-Robinson",
]

[tasks.ide-Robinson]
workspace = false
script = '''
./ide ./mlcfgs/Robinson.mlcfg
'''

[tasks.prove-Robinson]
workspace = false
dependencies = [
    "gen-cfg-Robinson",
    "ide-Robinson",
]

[tasks.creusot-CreuSAT]
workspace = false
command = "cargo"
args = ["creusot", "-p", "CreuSAT", "--features=contracts", "--features", "${@}"]

[tasks.move-CreuSAT]
workspace = false
script = '''
[ ! -f ./target/debug/CreuSAT-rlib.mlcfg ] || cp ./target/debug/CreuSAT-rlib.mlcfg ./mlcfgs/CreuSAT.mlcfg
'''

[tasks.gen-cfg-CreuSAT]
workspace = false
dependencies = [
    "creusot-CreuSAT",
    "move-CreuSAT",
]

[tasks.ide-CreuSAT]
workspace = false
script = '''
./ide ./mlcfgs/CreuSAT.mlcfg
'''

[tasks.prove-CreuSAT]
workspace = false
dependencies = [
    "gen-cfg-CreuSAT",
    "ide-CreuSAT",
]

[tasks.p]
workspace = false
dependencies = [
    "prove-CreuSAT",
]
args = [
    "${@}"
]

[tasks.build-musl]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo build --release --target x86_64-unknown-linux-musl
'''

[tasks.move-musl]
workspace = false
script = '''
cp ./target/x86_64-unknown-linux-musl/release/CreuSAT CreuSAT/StarExec/bin/creusat
'''

[tasks.make-zip]
workspace = false
script = '''
cd CreuSAT/StarExec && zip -r creusat.zip bin
'''

[tasks.build-musl-JigSAT]
workspace = false
script = '''
RUSTFLAGS='-C relocation-model=static' cargo build --release --target x86_64-unknown-linux-musl
'''

[tasks.move-musl-JigSAT]
workspace = false
script = '''
cp ./target/x86_64-unknown-linux-musl/release/JigSAT JigSAT/StarExec/bin/jigsat
'''

[tasks.make-zip-JigSAT]
workspace = false
script = '''
cd JigSAT/StarExec && zip -r jigsat.zip bin
'''

[tasks.StarExec]
workspace = false
dependencies = [
    "build-musl",
    "move-musl",
    "make-zip",
]

[tasks.StarExec-JigSAT]
workspace = false
dependencies = [
    "build-musl-JigSAT",
    "move-musl-JigSAT",
    "make-zip-JigSAT",
]

[tasks.clean-Friday]
workspace = false
script = '''
rm -rf mlcfgs/Friday*
'''

[tasks.clean-Robinson]
workspace = false
script = '''
rm -rf mlcfgs/Robinson*
'''

[tasks.clean-CreuSAT]
workspace = false
script = '''
rm -rf mlcfgs/CreuSAT*
'''

[tasks.clean-proofs]
workspace = false
dependencies = [
    "clean-Friday",
    "clean-Robinson",
    "clean-CreuSAT",
]
