max_width = 120
hard_tabs = false
newline_style = "Auto"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
fn_args_layout = "Compressed"
fn_single_line = true
