[package]
name = "JigSAT"
version = "0.1.0"
authors = ["Sarek Høverstad Skotåm <sarek.skotam@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["cargo"] }
log = "0.4"
rand = "0.8.5"

[dev-dependencies]
termcolor = "1.1"
