[package]
name = "NewDB"
version = "0.1.0"
authors = ["Sarek Høverstad Skotåm <sarek.skotam@gmail.com>"]
edition = "2021"


[dependencies]
creusot-contracts = { git = "https://github.com/xldenis/creusot", version = "^0", rev = "6a963bf" }
